stages:
  monitor:
    cmd: >-
      uv run churn-mlops monitor
      --reference_dataset ${monitoring.reference_dataset}
      --analysis_dataset ${monitoring.analysis_dataset}
      --source_reference ${monitoring.source_reference}
      --source_analysis ${monitoring.source_analysis}
      --output_dir ../data/monitoring/${monitoring.name}
      --model_name ${monitoring.model_name}
      --model_version ${monitoring.model_version}
      --mlflow_experiment_name ${monitoring.mlflow_experiment_name}
      --run_name ${monitoring.name}
      --reference_name ${monitoring.reference_name}
      --analysis_name ${monitoring.analysis_name}
    deps:
      - ../data/${monitoring.reference_dataset}
      - ../data/${monitoring.analysis_dataset}
      - ../src/churn_mlops
      - ../pyproject.toml
      - ../uv.lock
    params:
      - monitoring
    outs:
      - ../data/monitoring/${monitoring.name}
